import type { Metadata } from "next";
import "./globals.css";
import { Navbar, Footer } from "@/components/index ";

export const metadata: Metadata = {
  title: "KG_SALON",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="relative overflow-hidden">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
